name: empower_ananya
description: "Admin app for the EmpowerAnanya Foundation."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8

  # UI & Utility
  google_fonts: ^6.2.1
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  fl_chart: ^0.66.2 # *** NEW: Charting library added ***

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/empowerananya.jpg

